# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
displayName: db-testproject-CI
jobs:
- job: buildDacpac
  displayName: "Build dacpac"
  timeoutInMinutes: 10
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: VSBuild@1
    displayName: 'Build solution db-testproject/db-testproject.sln'
    inputs:
      solution: 'db-testproject/db-testproject.sln'
      msbuildArgs: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
      configuration: Release
      clean: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

- job: buildDocker
  displayName: "Build Docker image"
  dependsOn: buildDacpac
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      downloadType: specific
      itemPattern: 'drop/db-testproject.dacpac'
  - task: Docker@2
    displayName: docker build
    inputs:
      containerRegistry: devcg
      repository: 'db-testproject'
      command: build
      buildContext: '$(System.ArtifactsDirectory)'
      arguments: '--build-arg DACPAC_FILE=drop/db-testproject.dacpac'
      tags: |
        $(Build.BuildId)
        $(Build.SourceBranchName)
  - task: Docker@2
    displayName: docker push
    inputs:
      containerRegistry: devcg
      repository: 'db-testproject'
      command: push
      tags: |
        $(Build.BuildId)
        $(Build.SourceBranchName)